### ISSUE TITLE
Is binding event handlers supported?

### ISSUE THREAD

**Issue by gbcgit** [mbraak/django-mptt-admin#102]
Hello, 

Cool product.  Curious, is it possible to get the jQuery object that django-mptt-admin is using, and bind events to that?  I haven't been able to work it out myself yet.

I'm using Django and Django Grappelli, and in the admin, Grappelli puts jQuery on both a django and a grp variable, to make them accessible like this:  django.jQuery and grp.jQuery.    It then calls $.noConflict(true) which basically removes all global references to those jQuery instances.

At this point, django-mptt-admin, starts up fine, with its copy of jQuery.  However, when I try to add an event to the jqTree like this

    (function($) {
        $(document).ready(function() {
             $tree.bind(
                'tree.select',
                function(event) {
                    if (event.node) {
                        console.log(event.node.name+" was selected.");
                    } else {
                        console.log(event.previous_node + " was deselected.");
                    }
                });
        });
    })(<which jQuery?>);

I can't use grp.jQuery or django.jQuery, since the custom events like tree.select aren't defined on those jQuerys.  It seems also that no jQuery exists.  Is there a way to get the jQuery from django-mptt-admin to use here?  

I'm not too strong with JavaScript, so the solution might be simple.  Here some ideas I have

1)  Do something you guys recommend
2)  Clone the project, create a patch to somehow export the jQuery, or provide a jQuery to use, use that, give back to you guys for review.
3)  Clone the project, and add support for responding to the events I need right in the source, not sure the right way to do that yet, though.

In any case, thanks for the project, it's very helpful.   

Gene

**Comment by gbcgit** [comment]
After typing all this, I went back to play with it some more.  I ended up overriding a template and saving the defined jQuery right after it was loaded.  I was then able to use that for bind events.  Seems to work.  

My overridden change_list.html template looked like this:

        {% extends "django_mptt_admin/change_list.html" %}
        {% load i18n static %}

        {% block extrahead %}
            {{ block.super }}
            <script type="text/javascript">
                console.log("jq ver:  " + jQuery.fn.jquery);
                (function($) {
                    $(document).ready(function() {
                        var $tree = $('#tree');
                        console.log(tree);
                        $tree.bind(
                                'tree.select',
                                function (event) {
                                    if (event.node) {
                                        console.log(event.node.name + " was selected.");
                                    } else {
                                        console.log(event.previous_node + " was deselected.");
                                    }
                                }
                        );
                    })
                })(jQuery);
            </script>
        {%  endblock %}

This works.  It seems that when Django and Grappelli get to loading and messing with jQuery, where you are in the page load really matters.

**Comment by mbraak** [comment]
Thanks for the input. I had never thought of extending the javascript.

Greetings
