### ISSUE TITLE
Documentation pip installation error

### ISSUE THREAD

**Issue by fabiocaccamo** [mbraak/django-mptt-admin#108]
**`pip install django-mptt-admin`** instead of `pip install django_mptt_admin`

**Comment by mbraak** [comment]
Thanks for reporting this. I see that the official name is indeed `django-mptt-admin`. I will change this in the docs.

By the way, on my machine both `django-mptt-admin`. and `django_mptt_admin` work. I'm using pip version 7.1.2.

Which pip version are you using?

**Comment by mbraak** [comment]
This is now changed in the docs
