### ISSUE TITLE
Django Admin scripts don't included in the admin form

### ISSUE THREAD

**Issue by generalov** [mbraak/django-mptt-admin#112]
I have a mptt model with SlugField
```
# @python_2_unicode_compatible
class Category(MPTTModel):
    name = models.CharField(
        max_length=255)

    slug = models.SlugField()

    parent = TreeForeignKey(
        to='self',
        related_name='children',
        null=True, blank=True,
        db_index=True)

    class Meta:
        unique_together = [
            ('parent', 'name')
        ]

    class MPTTMeta:
        order_insertion_by = ['name']

    def __str__(self):
        return '{}'.format(self.name)
```
and DjangoMpttAdmin admin with a prepopulated field.
```
class CategoryAdmin(DjangoMpttAdmin):
    prepopulated_fields = {"slug": ("name",)}
```

Then I open /admin/app/category/add page, the slug field prepopulation doesn't work. I see an error message in the Javascript console:
```
Uncaught TypeError: $ is not a function
```

Django embeds a couple of scripts on the admin form page:
```
(function($) {
...
})(django.jQuery);
```
but django.jQuery doesn't defined beacuse jquery.init.js doesn't included into the page.

I tried to fix this with workaround:
```
class CategoryAdmin(DjangoMpttAdmin):
    prepopulated_fields = {"slug": ("name",)}

    @property
    def media(self):
        media = super(DjangoMpttAdmin, self).media
        extra = '' if settings.DEBUG else '.min'
        js = [
            'core.js',
            'vendor/jquery/jquery%s.js' % extra,
            'jquery.init.js',
            'admin/RelatedObjectLookups.js',
            'actions%s.js' % extra,
            'urlify.js',
            'prepopulate%s.js' % extra,
            'vendor/xregexp/xregexp.min.js',
        ]
        media.add_js(['admin/js/%s' % url for url in js])
        return media
```
( https://github.com/django/django/blob/master/django/contrib/admin/options.py#L568-L577 )

But then I got the `Uncaught TypeError: jQuery is not a function` from the `django_mptt_admin.js` because `jquery.init.js` install jQuery with a `noconflict` mode. 

I think, standard Django Admin scripts should be included anyway because they are used in the standard field widgets. 
If django_mptt_admin.js uses jQuery from Django Admin, it should call it as `django.jQuery`, not `jQuery`.

**Comment by mbraak** [comment]
I will try to reproduce this error.

**Comment by mbraak** [comment]
Thanks for reporting this issue!

I fixed this so the media are extended instead of replaced. The fix is in the `master` branch.

**Comment by generalov** [comment]
Thanks!

2016-02-09 20:30 GMT+05:00 Marco Braak <notifications@github.com>:
