### ISSUE TITLE
$tree.tree is not a function

### ISSUE THREAD

**Issue by felixSchl** [mbraak/django-mptt-admin#122]
I keep getting this error in the change list view:

```
Uncaught TypeError: $tree.tree is not a function
```

I followed the README and compared with the example projects. I can see no mistake. The scripts seem to load fine, the `jQuery('#tree')` result seems fine, but it has no `tree()` method. What could be going on here? I tred v.0.3.3 (c352ec0cc8ce4ca01fff3bec1ae721a209491147) as well as master but to no avail (except in master the error looks a bit different due to minifcation).

**Comment by felixSchl** [comment]
I just tested v0.3.1 (744bc6cd9d41423090a0bfdfc9b43a5d6a4bf2ac) and it works well, so it must have been introduced somewhere here: https://github.com/mbraak/django-mptt-admin/compare/744bc6cd9d41423090a0bfdfc9b43a5d6a4bf2ac...c352ec0cc8ce4ca01fff3bec1ae721a209491147

**Comment by mbraak** [comment]
I will try to reproduce the error.

Can you tell me which Django version you are using? And are you perhaps using an admin extension like Django Grappelli?

**Comment by felixSchl** [comment]
I am on django 1.8 and yeah I am using grapelli. I have not mentioned it because the HTML appears to get loaded correctly and so does the script.

**Comment by mbraak** [comment]
I tried to reproduce the error in the example project with grappelli 2.7.4 and Django 1.8.11. It all seems to work fine; both for django-mptt-admin 0.3.3 as the master branch.

**Comment by mbraak** [comment]
You can get the `tree is not a function` error if the `tree.jquery.js` is not loaded.

It is also possible that the `tree` function is connected to the wrong `jQuery` instance. This can happen if jquery is loaded multiple times.

**Comment by felixSchl** [comment]
@mbraak You were right, it was due to duplicate jquery depenency. I was bringing in jquery when I set up autocomplete_light at the time. Thank you for your time and my apologies for the noise. May it help someone else :)
