### ISSUE TITLE
django-mptt-admin: get expandable tree also for TreeForeignKey

### ISSUE THREAD

**Issue by mbraak** [mbraak/django-mptt-admin#127]
Dear Marco,

First of all thank you for django-mptt-admin. I'm new to django, so
perhaps I missed something that it is basic but I did not understand
how to do achieve what I want.
I would like to have a tree also when user have to select the Node for
TreeForeignField. I've look at the django-mptt-admin's documentation
but I didn't found it.
Is it feasible?
if yes which is the right way to do it with django-mptt-admin?
If no, perhaps you can suggest the right direction to implement this
functionality.

I've created a simple models.py like:

{{{
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey

class Nuts(MPTTModel):
   name = models.CharField(max_length=20, unique=True, db_index=True)
   label = models.CharField(max_length=100)
   parent = TreeForeignKey('self', null=True, blank=True,
                           related_name='children', db_index=True)

   class MPTTMeta:
       order_insertion_by = ['name']

   def __str__(self):
       return self.name + ' - ' + self.label

class Data(models.Model):
   name = models.CharField(max_length=20, unique=False, db_index=False)
   nuts = TreeForeignKey(Nuts, null=True, blank=True,
related_name='fk_nuts', db_index=True)
}}}

in the admin file I wrote:

{{{
from django.contrib import admin
from django_mptt_admin.admin import DjangoMpttAdmin
from nuts.models import Nuts, Data

class NutsAdmin(DjangoMpttAdmin):
   tree_auto_open = 0
   tree_load_on_demand = True

admin.site.register(Nuts, DjangoMpttAdmin)
admin.site.register(Data, DjangoMpttAdmin)
}}}

Any hint?

Best regards

Pietro

**Comment by mbraak** [comment]
Hello Pietro,

If I understand you correctly you want to display a tree in an admin form. Is that correct?

Greetings,
Marco

**Comment by zarch** [comment]
Just to make things easier to read, NUTS stay for [Nomenclature of territorial units for Statistics](http://ec.europa.eu/eurostat/web/nuts/overview), ad here the formatted code for models.py:

```
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey

class Nuts(MPTTModel):
    name = models.CharField(max_length=20, unique=True, db_index=True)
    label = models.CharField(max_length=100)
    parent = TreeForeignKey('self', null=True, blank=True,
                            related_name='children', db_index=True)

    class MPTTMeta:
        order_insertion_by = ['name']

    def str(self):
        return self.name + ' - ' + self.label

class Data(models.Model):
    name = models.CharField(max_length=20, unique=False, db_index=False)
    nuts = TreeForeignKey(Nuts, null=True, blank=True,
                          related_name='fk_nuts', db_index=True)
```

and admin.py:

```
from django.contrib import admin
from django_mptt_admin.admin import DjangoMpttAdmin
from nuts.models import Nuts, Data

class NutsAdmin(DjangoMpttAdmin):
    tree_auto_open = 0
    tree_load_on_demand = True

admin.site.register(Nuts, DjangoMpttAdmin)
admin.site.register(Data, DjangoMpttAdmin)
```

**Comment by mbraak** [comment]
I see what you mean. I'm afraid you can't do that with django-mptt-admin.

I can't really help with you, but I can point you to some resources:

* The [https://github.com/django-ckeditor/django-ckeditor](django-ckeditor) package is an example of a custom widget for the Django admin.
* Django-mptt-admin uses the [jqtree](https://github.com/mbraak/jqTree) javascript library which is also written by me.

**Comment by panqjhust** [comment]
Dear Marco,
     in html,  there are edit/add methods,  which are tree relative.  how to append a method which has nothing with the tree?
     for example, to one tree element, execute other task, using python, in Django  environment.

**Comment by mbraak** [comment]
Hello Panqjhust,

Can you give an example of a task?

Greetings,
Marco

**Comment by panqjhust** [comment]
Dear Marco,
Knowing nothing about frontend, sorry, must be lack of knowledge.
in this github code page,  there is an example that show earth tree:
root
     africa
     ameria
     asia
my question is about appending external info to each elem, such as  area, population, weather, and so on.  current task have edit/add.
Maybe it was usesage of mptt, and  i shouldnot make this question,

**Comment by mbraak** [comment]
So, you want to display extra info:

```
root
    africa (1.1 billion)
    asia (4.4 billion)
```

I think that's possible. Let me see if I can find an example.

**Comment by zarch** [comment]
Instead display something like:
 ```
root
    africa
        niger
        congo
        ...
    europe
        belgium
        Italy
        ...
    ...
```

This is not possible, right?

**Comment by panqjhust** [comment]
Yes, it should be enable link as edit/add , so can be operated.  Info display anywhere,  can be subpage, or in the same line as `africa (1.1 billion)` .Current edit is subpage, and url is relatived.

**Comment by mbraak** [comment]
@panqjhust 

I now see what you mean. No, django-mptt-admin does not support that.

You can of course write it yourself in javascript. But then you have to change the `django_mptt_admin.js` file. If you want to do that, I can refer you to the [jqtree](https://mbraak.github.io/jqTree/) library, which is the underlying javascript library for django-mptt-admin.

**Comment by mbraak** [comment]
@zarch 

If I understand you correctly, then you want to display a tree in a Django form. You can't do that with django-mptt-admin, because that is not its use case.

**Comment by panqjhust** [comment]
Right,  `django-mptt-admin depends on django-mptt models`.   My task is to show tree not in admin model,  and append extral in tree , shoul i make how many changes, just using python django and jqtre. Please give your suggestion.

**Comment by mbraak** [comment]
@panqjhust 

That sounds like a very interesting task! You're the first to try something like this with django-mptt-admin, so I don't know what to advice you.

My first suggestion would be to have a look at the [django-mptt-admin javascript code](https://github.com/mbraak/django-mptt-admin/tree/master/frontend) and see if you can build it yourself. It uses the [gulp](http://gulpjs.com/) build system.

Note that this requires knowledge in javascript.
