### ISSUE TITLE
Change detail page collapse issue

### ISSUE THREAD

**Issue by sunjoomoon** [mbraak/django-mptt-admin#135]
Collapse is NOT collapsed.

Seems below js 
```
<script type="text/javascript" src="/static/django_mptt_admin/jquery_namespace.js"></script>
<script type="text/javascript" src="/static/django_mptt_admin/django_mptt_admin.js"></script>
```
Conflicts with django admin change detail page, collapse feature. HTML source is as below. It is NOT collaped.
```
<fieldset class="module aligned collapse">
    <h2>Image Title &amp; Layout Option</h2>
    
    
        <div class="form-row field-image_title">
```

Admin.py related scripts are
```
        (_('Image Title & Layout Option'), {
            'classes': ('collapse',),
            'fields': ('image_title','image_sub_title','image_column_type'),            
        }),   
```

Anywork around?

**Comment by sunjoomoon** [comment]
Figured out it was because of js conflict - ckeditor and mptt-admin js. So, here is the work around. In jquery_namespace.js file, make it look like below. Just added ```$.noConflict();``` 
```
$.noConflict();
window.$ = django.jQuery;
window.jQuery = django.jQuery;
```
Further information http://api.jquery.com/jQuery.noConflict/

**Comment by sunjoomoon** [comment]
Sorry, above seemed okay but back in the tree list page, nothing is shown. Still somehow ckeditor and tree llist conflicts. When I change ckeditor with tinymce editor, then this issue is resolved. So, surely something to do with ckeditor & tree list.

Any idea where to look for?

**Comment by mbraak** [comment]
Are there are any error messages in the console log of your browser?

**Comment by sunjoomoon** [comment]
No errors are shown at all. Just silently nothing is rendered/ shown in the tree list page.
1) if I use ckeditor & tree list - then django collapse is NOT working - all open ( can not collapse or uncollapse
2) if I use tinymce & tree list - all fine. Collpase works as usual
3) if I put noConflict in ```jquery_namespace.js```, then tree list shows nothing. Html source code shows nothing (tree list) is rendered

**Comment by mbraak** [comment]
How are you including ckeditor? Are you using a django-app?

**Comment by mbraak** [comment]
Closing this now
