### ISSUE TITLE
Templatetags for top children menu...

### ISSUE THREAD

**Issue by sunjoomoon** [mbraak/django-mptt-admin#136]
I have something like below. Using django-parler, mptt
```
class Menu(MPTTModel, TranslatableModel):
    parent = models.ForeignKey('self', null=True, blank=True, related_name='children')     
    translations = TranslatedFields(
        title = models.CharField(_('title'), max_length=255, unique=True),
        slug = models.UnicodeSlugField(_('slug'), unique=True),
        hint = models.CharField(_('hint'),  max_length=255, null=True, blank=True),
    )
```

I can get the entire trees as below
```
<ul> 
    {% recursetree page_list %}
    <li>
    <a href="{{ node.get_absolute_url }}">{{ node.title }}</a> 
        {% if not node.is_leaf_node %}
        <ul>
        {{ children }}
        </ul>
        {% endif %}
    </li>
    {% endrecursetree %}
</ul>
```

Now how do I get 'sibling & child' trees?  What I am trying to do is to have a small menu app, using  django-mptt-admin. Thus, in a situation like below
```
Home
Company
- History
- Background
- Location Map
```
If I am at 'background', I wish to display 'history, background, location map' in the side menu - and display the root page 'Company' page as well. 

Any example?

**Comment by mbraak** [comment]
If you want to display a tree menu, then I can recommend the [jqTree](https://mbraak.github.io/jqTree/) javscript library.

**Comment by mbraak** [comment]
Does this work? Closing the issue for now
