### ISSUE TITLE
Filter the tree in tree view

### ISSUE THREAD

**Issue by xrmx** [mbraak/django-mptt-admin#170]
I'd like to being able to show only a subset of the tree in tree view. Using the example models on the README i want to display only a single continent and being able to add, edit and shuffle countries. 
To avoid any potential issue with the data i think this could be even be handled on the js side by just hiding the part of the tree we have filtered out.
What do you think?

**Comment by mbraak** [comment]
You could override the `filter_tree_queryset` function:

```python
class CountryAdmin(DjangoMpttAdmin):
  def filter_tree_queryset(self, queryset):
    return queryset.filter(name='abc')
```

Please let me know if this is a good solution for you!

**Comment by xrmx** [comment]
One thing i missed is that the filter must be done by the user, so that could be used if we show the grid view filter column in the tree view too. Will give it a try, thanks for the hint.

**Comment by xrmx** [comment]
So finally got time to take a look at this, here's the hacks i needed:
https://github.com/xrmx/django-mptt-admin/commit/953422d224629f3cc52cc05c54c920548d09a991

Do you see something that can be improved / merged? Thanks!

**Comment by mbraak** [comment]
Thanks! I will have a look at it.

**Comment by mbraak** [comment]
I merged this into the project. Thank you again for this!

**Comment by xrmx** [comment]
Cool! Looking forward to a new django-mptt-admin release then :)
