### ISSUE TITLE
support preserved filters in FilterableDjangoMpttAdmin

### ISSUE THREAD

**Issue by xrmx** [mbraak/django-mptt-admin#185]
At the moment adding and editing urls from a FilterableDjangoMpttAdmin change list will trash any filter and so after save the filter will be lost. It would be nice to support preserved filters so that will work.

Reference:
https://github.com/django/django/commit/c86a9b63984f6692d478f6f70e3c78de4ec41814

I'm trying to take a look at this but am not sure i'll come up with something working generally.

**Comment by mbraak** [comment]
I see the issue. I also noticed that the filter is lost when you go to the 'grid view'.

**Comment by mbraak** [comment]
I fixed this in the `master` branch.

**Comment by xrmx** [comment]
Thanks for changes! master does not appear to work fine here with django 1.8:

```
  File "/venv/local/lib/python2.7/site-packages/django_mptt_admin/util.py", line 63, in get_tree_from_queryset
    parent_id = getattr(instance.parent, pk_attname)
AttributeError: 'NoneType' object has no attribute 'id
```
Adding a debug print i get:
instance has no parent instance.level 0 min_level 1

so for some reason we have a min_level of 1 instead of 0 and when we get the root node it explodes.

**Comment by xrmx** [comment]
This apepar to work for me:

```
diff --git a/django_mptt_admin/util.py b/django_mptt_admin/util.py
index d4aaa90..1a214c9 100644
--- a/django_mptt_admin/util.py
+++ b/django_mptt_admin/util.py
@@ -33,6 +33,8 @@ def get_tree_from_queryset(queryset, on_create_node=None, max_level=None, item_l
     for instance in queryset:
         if min_level is None:
             min_level = instance.level
+        elif instance.level < min_level:
+            min_level = instance.level
 
         pk = getattr(instance, pk_attname)
 
```

**Comment by mbraak** [comment]
That is strange. I don't get this error.

Have you set some options like `tree_auto_open` or `tree_load_on_demand`?

**Comment by xrmx** [comment]
nope, i don't have any tree related option. Btw there's another regression, self.get_insert_at_field() now returns 'parent' but the ui uses 'inserted_at'.

**Comment by mbraak** [comment]
I fixed the 'insert at' bug. It was a bug in the javascript.

**Comment by mbraak** [comment]
I also added the code fragment you mentioned, although I don't get the error

**Comment by xrmx** [comment]
Latest master appear to work fine for me. Thanks a lot!

**Comment by xrmx** [comment]
@mbraak any chance you can cut a new release please?

**Comment by mbraak** [comment]
I plan to do a new release next week.

**Comment by mbraak** [comment]
Version 0.4.4 is released

**Comment by xrmx** [comment]
@mbraak thanks a lot!
