### ISSUE TITLE
Handle CSRF_COOKIE_NAME option

### ISSUE THREAD

**Issue by mbraak** [mbraak/django-mptt-admin#188]
The CSRF_COOKIE_NAME option in Django changes the cookie name. Django-mptt-admin should handle that correctly.

**Comment by mbraak** [comment]
This is fixed in the master branch

**Comment by xrmx** [comment]
I don't see it

**Comment by mbraak** [comment]
The latest version is now pushed to github. Note that this fix is not in the 0.4.4 release

**Comment by xrmx** [comment]
Sure, was just pointing you forgot to push to github :)
