### ISSUE TITLE
JS exception in change_form mode

### ISSUE THREAD

**Issue by absinsekt** [mbraak/django-mptt-admin#191]
Thank you for great plugin, in list view everything is ok, but there's a pity bug in change form view.
I have no #tree elements on edit page and there's no use to load django_mptt_admin.js on it, but the script loads, js crushes disabling my other javascripts.

http://prntscr.com/e9amul
http://prntscr.com/e9amua

Unfortunately script is minified, but something like that could be a dirty hack.

http://prntscr.com/e9amum

**Comment by mbraak** [comment]
Thanks for reporting this. I will have a look at it.

**Comment by mbraak** [comment]
I added a bugfix to the `master` branch.

This should fix it, but I cannot be completely sure, because I could not reproduce the error myself.

**Comment by absinsekt** [comment]
Don't you get an error if try to edit some entity from drag-n-drop mptt list?

**Comment by mbraak** [comment]
No, perhaps i'm using a different Django version. I tested it with Django 1.10.5 on Google Chrome.

**Comment by absinsekt** [comment]
Django 1.10.15, Python 3.6
Perhaps is the reason in tinymce also used in my model (jquery conflict or something like that)
So is my model followed by admin "config":
```
class ProductCateory(MPTTModel):
    parent = TreeForeignKey('self', blank=True, null=True, related_name='children', db_index=True)
    slug = models.SlugField(unique=True)
    title = models.CharField(max_length=250, blank=False)
    description = HTMLField(blank=True)
    is_published = models.BooleanField(default=False)

    def __str__(self):
        return self.title
```

admin.py

```
@admin.register(ProductCategory)
class ProductGroupAdmin(DjangoMpttAdmin):
    tree_auto_open = False
    tree_load_on_demand = None
    list_display = ('parent', 'title', 'is_published')
    list_display_links = ('parent', 'title')
    list_editable = ('is_published',)
    ordering = ('title',)
```
