### ISSUE TITLE
pagination is invalid

### ISSUE THREAD

**Issue by boylegu** [mbraak/django-mptt-admin#205]
Hi friend:
    I found that pagination is invalid and too slow. 

![image](https://user-images.githubusercontent.com/9545038/27391491-aa438ae4-56d6-11e7-984e-95b70c972549.png)
![qq20170621-0](https://user-images.githubusercontent.com/9545038/27391807-82266198-56d7-11e7-8fcf-9df7cec1b659.png)

Where can I go for help? Thanks

**Comment by mbraak** [comment]
Hello Boylegu,

That looks strange indeed. What does your Django model look like?

Cheers,
Marco

**Comment by boylegu** [comment]
models.py
~~~python
class IntegratorGroup(MPTTModel):
    name = models.CharField(max_length=20, unique=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)
    people = models.ManyToManyField('IntegratorUser',  null=True, blank=True)
~~~

admin.py
~~~python
class IntegratorGroupAdmin(DjangoMpttAdmin):
    mptt_level_indent = 20
    filter_horizontal = ("people",)
    list_filter = ('people__integrator_username',)
......
admin.site.register(IntegratorGroup, IntegratorGroupAdmin)
~~~
In addition， my development environment：
- django 1.9.5
- django-mptt 0.8.7
- django-mptt-admin 0.4.6
- django-grappelli==2.8.3   (admin style)

**Comment by mbraak** [comment]
Django-mptt-admin was not tested with django-grappelli. If you do use grappelli, this will cause some issues. One of these issues is apparently the pagination.

**Comment by boylegu** [comment]
Unfortunately! Un...  Do you think about compatible with django-grappelli in next version?

**Comment by mbraak** [comment]
Sorry, I have no plans for that at this moment.

**Comment by boylegu** [comment]
ok. Thanks ~
