### ISSUE TITLE
set default view to grid (instead of tree)

### ISSUE THREAD

**Issue by sdementen** [mbraak/django-mptt-admin#208]
hello, is it possible via some options or attribute in the admin class to have as default view the grid view and the tree as option ? so the opposite behavior of today where default is tree and to view the grid, there is the "grid view" button.

**Comment by mbraak** [comment]
At this moment there is no such option.

**Comment by sdementen** [comment]
could you point me where to look for if I want to override this ? tx!

**Comment by mbraak** [comment]
Perhaps you can override the [get_urls](https://github.com/mbraak/django-mptt-admin/blob/master/django_mptt_admin/admin.py#L127) function

**Comment by mbraak** [comment]
Closing the issue. Feature is not added.

**Comment by wangyinhu** [comment]
I need this feature. I think this is useful
