### ISSUE TITLE
Adding a spinner for move

### ISSUE THREAD

**Issue by xrmx** [mbraak/django-mptt-admin#224]
On big trees moving could take seconds and currently there's no visual feedback that there's something working under the hood. What do you think on adding a spinner?

**Comment by mbraak** [comment]
Sorry, at this moment I don't have time to add new features.

**Comment by xrmx** [comment]
I was not asking for you to do the work :) I was asking if you are willing to accept a PR doing that, thanks!

**Comment by mbraak** [comment]
Sure. I will accept a pr to do that.
