### ISSUE TITLE
tree_auto_open = False doesn't work.

### ISSUE THREAD

**Issue by Martin317** [mbraak/django-mptt-admin#256]
Hello, I'm trying to display only the first level of the tree. 
The options tree_auto_open, use_context_menu and  tree_load_on_demand doesn't work for me. 
Am I doing something wrong? 

```
class TemarioAdmin2(DjangoMpttAdmin):
    tree_auto_open = False
    tree_load_on_demand = 0
    use_context_menu = 1
```
Thanks!

**Comment by mbraak** [comment]
Hello,

I think you have to set `tree_auto_open` to `0`. Note that the tree saves the state to the local storage. So you might have to clear the local storage to test this properly.

I tested this with:

```python
class CountryAdmin(DjangoMpttAdmin):
    tree_auto_open = 0
    tree_load_on_demand = 0
    use_context_menu = True
```

Another detail: `use_context_menu` should be `True` or `False`

Cheers,
Marco

**Comment by Martin317** [comment]
It works. It was the local storage. I think context menu isn't working. Thanks!

**Comment by mbraak** [comment]
closing the issue
