### ISSUE TITLE
Using django admin's search_fields

### ISSUE THREAD

**Issue by TuuleSober** [mbraak/django-mptt-admin#262]
Hey!

Is it possible to use django admin's `search_fields` on a descendant of `DjangoMpttAdmin`? I have added some search field values onto my admin, but the search box does not show up on the admin site.

I did see that the admin template does have the search-block present, but also `DjangoMpttAdmin` seems to always send an empty tuple to django admin's `ChangeList` - hence my confusion.

thanks!

**Comment by mbraak** [comment]
I will have a look at it.

**Comment by mbraak** [comment]
I'm afraid the `search_fields` option is not supported at this moment.

However, there is a `branch` with partial support. I'm not working on this feature at the moment, but feel free to work on it. The branch is https://github.com/mbraak/django-mptt-admin/tree/search-fields

**Comment by TuuleSober** [comment]
thank you for the quick response and update!
