### ISSUE TITLE
Tree view is not playing well with html string

### ISSUE THREAD

**Issue by RecNes** [mbraak/django-mptt-admin#268]
Here is the model class with string method declaration:

```
class Menu(MPTTModel):
    """
    Menu database
    """
    icon = IconField()
    name = models.CharField(max_length=50, unique=True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    def __str__(self):
        return mark_safe('{}&nbsp;&nbsp;&nbsp;{}'.format(self.icon.as_html(), self.name))

    class MPTTMeta:
        order_insertion_by = ['name']
        verbose_name = _('Menu')
        verbose_name_plural = _('Menus')

```
As you can see, the __str__ declaration result is marked as safe because of the output has html tags.

And admin class:

```
@admin.register(Menu)
class MenuAdmin(DjangoMpttAdmin):

    class Media:
        js = ('fontawesome_5/js/all.min.js',)

        css = {
            'all': ('fontawesome_5/css/all.min.css',)
        }

```

While table view can display font awesome icons well, tree view is displaying icons as raw html like below:

`<span class="jqtree-title jqtree_common" role="treeitem" aria-level="2" aria-selected="false" aria-expanded="false">&lt;i class="fas fa-home " &gt;&lt;/i&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;Home</span>`

**Comment by mbraak** [comment]
I will look into it.

**Comment by mbraak** [comment]
I think you can use the `autoescape ` option:

```
class MenuAdmin(DjangoMpttAdmin):
  autoescape = False
```

Also see https://mbraak.github.io/django-mptt-admin/#options

**Comment by RecNes** [comment]
Oh! I totally missed that option. I'll try and let you know the result.

**Comment by RecNes** [comment]
Ok, adding `autoescape` to admin is made the code interpreted HTML tags correctly. But now, I discovered js and css files stated in `Media` class are not loading when switched to _tree view_ . The browser's developer tool confirms those files are not received, but in normal view.

**Comment by mbraak** [comment]
`Media` classes are not supported at the moment. I will see if I can add that feature.

**Comment by mbraak** [comment]
I added a pull request for this feature. Could you try this in your project? @RecNes

**Comment by mbraak** [comment]
Merged.

**Comment by mbraak** [comment]
New version 0.7.2 supports media classes

**Comment by RecNes** [comment]
Well done. It's working like a charm. Thank you very much and sorry for the late reply.
