### ISSUE TITLE
unknown setting DJANGO_MPTT_ADMIN_COVERAGE_JS

### ISSUE THREAD

**Issue by andrkhr** [mbraak/django-mptt-admin#327]
Greetings!

After updating to version 2.0.1, when opening the page with the tree of objects, we get an error `AttributeError: 'Settings' object has no attribute 'DJANGO_MPTT_ADMIN_COVERAGE_JS'`.

This is solved by adding in `settings.py` `DJANGO_MPTT_ADMIN_COVERAGE_JS=False`, but it looks like it's more of a test parameter.

**Comment by mbraak** [comment]
I will have a look.

**Comment by mbraak** [comment]
This is fixed in version 2.0.2
