### ISSUE TITLE
Is it possible to forbid drag and drop for specified users or groups?

### ISSUE THREAD

**Issue by Lorloz** [mbraak/django-mptt-admin#345]
Hello there, I've came across with this task as some of our users in Django admin must not have the ability to change or accidentally change the order or the level of model instances.

I think this would be a nice and helpful additional functionality for this awesome app.

**Comment by mbraak** [comment]
I could add a `is_readonly` method that you can override. In the case of readonly the drag-and-drop function would be disabled.

```python
class CountryAdmin(DjangoMpttAdmin):
  def is_readonly(self):
    return False # default is True
```

Is this a solution in your situation?

**Comment by Lorloz** [comment]
Thanx for quick reply!

That would be perfect, i will just then check:

```python
if request.user.groups.filter(name='some_group').exists():
    return True
return False
```

**Comment by mbraak** [comment]
I see that `ModelAdmin` has a `has_change_permission` method. I would rather use that existing method than adding a new one. Also see https://docs.djangoproject.com/en/3.1/ref/contrib/admin/

Code would like this.

```python
def has_change_permission(self, request, obj=None):
    return request.user.is_superuser
```

**Comment by Lorloz** [comment]
The problem is, if the user don't have change permission for the required model, he can't edit or list model instances.

That's because the func `changelist_view` of the `DjangoMpttAdminMixin` has the following:

```python
if not self.has_change_permission(request, None):
    raise PermissionDenied()
```

My task is only to forbid drag and drop at jstree view, meanwhile the user must have the ability to continue editing model instance fields.

I've made some monkey patching and now have the desired result.

I pass `can_move` variable to `change_list` template, and then get the `data-move` attribute in js script.

This enables me to pass `dragAndDrop: $tree.data("move"),` to `treeOptions` dict.

**Comment by mbraak** [comment]
Ok, then I think it's better to add a `is_drag_and_drop_enabled` method.

```python
def is_drag_and_drop_enabled(self):
  return False  # default is True
```

**Comment by mbraak** [comment]
There is a pr to add the `is_drag_and_drop_enabled` method: #347. Will be merged shortly.
