### ISSUE TITLE
django-mptt-admin no longer works in Django 3.2 since 6736363ff399cdd93679ca96b6e8512f63962ee6

### ISSUE THREAD

**Issue by scottp-dpaw** [mbraak/django-mptt-admin#541]
The change_list template adds a reference to ```{% static 'admin/js/filters.js' %}```, which is a file I believe was only added in Django 4.1 - https://github.com/django/django/commit/27aa7035f57f0db30b6632e4274e18b430906799

**Comment by mbraak** [comment]
I'll have a look

**Comment by mbraak** [comment]
Work in progress in #542

**Comment by mbraak** [comment]
This is fixed in pull request #542. I plan to merge the fix this week.

**Comment by mbraak** [comment]
In the title you mention that django-mptt-admin no longer works, but I couldn't reproduce that when testing in Django 3.2. I only saw that the filters.js couldn't be loaded.

**Comment by mbraak** [comment]
The pr is merged. I plan to release a new version soon.

**Comment by mbraak** [comment]
This is fixed in version 2.6.2
