### ISSUE TITLE
when using custom admin site, "add" url is not resolved properly

### ISSUE THREAD

**Issue by chenull** [mbraak/django-mptt-admin#56]
Hi,

I have a "custom" django admin site, which is instantiate as below:

```
class UserAdmin(AdminSite):
    login_form = AuthenticationForm
    def has_permission(self, request):
        return request.user.is_active

manage = UserAdmin(name='manage')
```
and my urls.py as:
```
...
    (r'^manage/', include(manage.urls)),
...
```

Then when i tried to do "add" action, the url resolved '/admin/' instead of '/manage/'
But, in the "grid view" it resolved correctly ('/manage/')
Please see attachment to see clearly what i meant:

I've tried debugging and find my self no answer how to resolve the "add" url correctly
![screen shot 2015-01-26 at 11 08 14 pm](https://cloud.githubusercontent.com/assets/1737556/5902981/88f10b10-a5b1-11e4-86f9-09f9112401a1.jpg)

**Comment by mbraak** [comment]
Hello,

I could not reproduce this error. I get the correct url.

Which Django version are using?

Greetings

**Comment by chenull** [comment]
Django 1.7.3

**Comment by mbraak** [comment]
I'm also using 1.7.3.

This is the test code that I used:

example_project/django_mptt_example/admin.py:

```python
from django.contrib.admin import AdminSite

from django_mptt_admin.admin import DjangoMpttAdmin

from .models import Country


class UserAdmin(AdminSite):
    pass


class CountryAdmin(DjangoMpttAdmin):
    tree_auto_open = 0
    list_display = ('code', 'name')
    ordering = ('name',)


admin = UserAdmin(name='manage')

admin.register(Country, CountryAdmin)
```

example_project/example_project/urls.py:

```python
from django.conf.urls import patterns, include, url

from django_mptt_example.admin import admin

urlpatterns = patterns(
    '',
    url(r'^manage/', include(admin.urls)),
)
```

**Comment by chenull** [comment]
hm.. yeah i can confirm too that your code is working. so it must be somewhere else on my code. thank you anyway :)
