### ISSUE TITLE
Since update to 2.7.0 "item_label_field_name" does not display HTML tags anymore 

### ISSUE THREAD

**Issue by hfx** [mbraak/django-mptt-admin#597]
Adding html tags to the title of each node shown in the tree does not work anymore after updating django-mptt-admin to 2.7.0 (with Django 4.2 and django-mptt 0.16.0).

Pointing `item_label_field_name` in the admin to a property function defined at the model which returns html (using either `mark_safe() `or `format_html()`) returns now escaped html.

Example:

```
# models.py
@property
def title_for_admin_tree_url(self):
        return format_html('<a href="www.example.com">abcd</a>')

# admin.py
autoescape = False
item_label_field_name = 'title_for_admin_tree_url'
```
This produces no clickable link per node, but the string `<a href="www.example.com">abcd</a>`

The problem is similiar to #268 and #352, but the solution – `autoescape = False` in the admin class – does not work anymore.

**Comment by mbraak** [comment]
I'll have a look.

**Comment by mbraak** [comment]
I can't reproduce the error. I tested with the changes from your example, Django 5.1.3 and django-mptt-admin 2.7.0.

![Scherm­afbeelding 2024-12-04 om 08 47 28](https://github.com/user-attachments/assets/23f0f510-1a65-4f3e-89d4-e3653e0da820)

**Comment by hfx** [comment]
Thank you for looking into this. Unfortunately even after updating to Django 5.1.3 the error still exists in my setup. I also tested without django-grappelli which I also use, but to no avail. I will try to debug it further.
