### ISSUE TITLE
Make inclusion of jQuery optional; might be a duplicate

### ISSUE THREAD

**Issue by joelburton** [mbraak/django-mptt-admin#63]
Some admin skins already include jQuery; having the changelist_view include it itself will often break or, at best, be an unnecessary inclusion.

Would it be possible to add a settings variable for this, so configurators can choose not to have you include your own private jQuery?

**Comment by joelburton** [comment]
(This could be made easier if your changelist_view() method used the extra_context passed to it; currently it ignores it, making it difficult for the DjangMpttAdmin subclass to try to do this itself. This could be fixed by adding

        context.update(extra_context or {})

to your changelist_view() method)

**Comment by mbraak** [comment]
Hello,

I could certainly add an option, something like ``include_jquery``. The default would be ``true``.

Which admin skin are you using?

Greetings
