### ISSUE TITLE
Other models get not listed in tree

### ISSUE THREAD

**Issue by zout** [mbraak/django-mptt-admin#98]
I have different types of models that will be combined in one tree. But the admin does not seem to understand...

Here are my models:
class Structure(MPTTModel):
    title = models.CharField(max_length=255)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='structures', db_index=True)

    def __str__(self):
        return self.title

class StructureArticleItem(MPTTModel):
    article = models.ForeignKey(Article)
    presentation = models.IntegerField(choices=STRUCTURE_ARTICLE_PRESENTATION, default=1)
    parent = TreeForeignKey(Structure, null=True, blank=True, related_name='article_items', db_index=True)

    def __str__(self):
        return self.article.title

class StructureWebItem(MPTTModel):
    url = models.URLField()
    parent = TreeForeignKey(Structure, null=True, blank=True, related_name='web_items', db_index=True)

Is this a missing feature, or is it not able to find the missing models?

**Comment by mbraak** [comment]
I cannot find anything about multiple models in the [django-mptt documentation](http://django-mptt.github.io/django-mptt/index.html). Are you sure this is supported?

If django-mptt supports it, then django-mptt-admin should also support it.

**Comment by zout** [comment]
After some searching I found out it relies very heavy on the Django QuerySet system, and that won't work the way I need it. Thanks for the quick help!

This is where i found it:
http://stackoverflow.com/questions/11108462/django-mptt-leaf-nodes-of-multiple-types
